### ISSUE TITLE
YouTube Account Name (Suggestions/Ideas Welcome!) ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/video#11]
If `dwyl` is _available_ we should go for it, otherwise `dwylhq` ? (_unless anyone has a better suggestion..._)
@iteles which email address should we use to manage the account?

**Comment by nelsonic** [comment]
so, we were able to register our account with the name `dwyl` ✅

**Comment by sohilpandya** [comment]
So I have still not received the invitation, so unable to upload/edit any of the information on the [here](https://www.youtube.com/channel/UCItdEQk0-lGLm8JhOfoLxkQ) 😢 

Has @iteles received the invite? Just wanted to check if it was me or everyone 😬

**Comment by nelsonic** [comment]
@sohilpandya good question... @iteles ⬆️  (_did you receive an invite from YouTube to manage the channel?_)

**Comment by iteles** [comment]
@nelsonic Yes and @sohilpandya is listed as invited:
<img width="687" alt="screen shot 2016-12-06 at 15 16 37" src="https://cloud.githubusercontent.com/assets/4185328/20930883/0a155836-bbc7-11e6-9bd9-d64bfc393278.png">

Do you know whether you invited the correct email address of Sohil's ?

**Comment by sohilpandya** [comment]
That's strange. I haven't received anything. (my YT account is linked to this email -> sohilpandya1990@gmail.com but received nothing there 👎)

Could you please delete me and try again? 🙏

**Comment by iteles** [comment]
@sohilpandya Done!

**Comment by sohilpandya** [comment]
Nope, still not working. 

I have now followed this guide found here - https://www.en.advertisercommunity.com/t5/Ownership-Conflicts/Manager-invite-emails-will-not-go-through/td-p/493216# 

Could you please invite me one more time? see if it works.

**Comment by nelsonic** [comment]
@sohilpandya let's look at this tomorrow morning (_or when you are next in HQ so we can call Google/YouTube support if needed..._)

**Comment by sohilpandya** [comment]
Yeah, lets do that. 👍

**Comment by sohilpandya** [comment]
Thanks @iteles for sorting this out! :)

**Comment by nelsonic** [comment]
https://www.youtube.com/@dwyler
<img width="1406" alt="image" src="https://github.com/user-attachments/assets/117aa68e-04bd-4f3e-904e-f5c62b1811ba">
