### ISSUE TITLE
What do we need to make #16 into (The Best Temporary/Weekend) Tech Classroom?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/video#13]
I quite like the _style_ of Harvard CS50 videos: https://youtu.be/MJUJ4wbFm_A
![intro-to-git-and-github-harvard-cs50](https://cloud.githubusercontent.com/assets/194400/21466850/3e46efdc-c9cf-11e6-8d53-83dd71234481.png)

They have:
+ a "**lectern**" where the speaker/instructor places their laptop while they are delivering the content
+ **Big Screen** where people in the RL audience can see _exactly_ what the presenter is talking about.
+ **Lavalier Microphone** to capture sound in as much quality as possible: https://github.com/dwyl/video/issues/5
+ **Lighting** see: https://github.com/dwyl/video/issues/14
+ **HDMI** splitter so the image/presentation can be displayed on at least one "Big Screen" and run the signal through the video capture device. e.g: https://www.amazon.co.uk/Splitter-SOWTECH-Input-Outputs-Support/dp/B019MRGGJU
+ **HDMI** video capture device to record the screen of the presenter so we can display it in the video.

_Please_ ***help*** put together our "***list***" of what would make `#16` the _perfect_ classroom to do a workshop for our clients? see: 

> @harrygfox / @sohilpandya you have run weekend workshops in the past, what "worked well"? and if time/money were "no object" what would you do to make the workshop venue "_World Class_"?
Thanks! ❤️

**Comment by sohilpandya** [comment]
@nelsonic I ❤️  this! 😄 

Lighting is a key aspect, and I'm talking about the space. I still feel that it's too **dark** in no. 16 even when we are working. Would it be possible to somehow make the space brighter? (I don't think the 6-10 LED lights we have in the place do it justice. 😢)

I think we are running another one in the new year, so will make some notes and put them on here for everyone to read! :)

**Comment by nelsonic** [comment]
@sohilpandya the Lighting in `#16` needs to be _addressed_ ***comprehensively***: https://github.com/dwyl/hq/issues/156

**Comment by nelsonic** [comment]
@sohilpandya how sick is this projector: https://youtu.be/9TS9Hsa6iCg

**Comment by sohilpandya** [comment]
@nelsonic it looks awesome! I've played with a few touch projectors in John Lewis before and no where near as responsive as the one in the video above. 

Having said that, I am still unsure how useful this will actually be for day to day use.

**Comment by nelsonic** [comment]
@sohilpandya I tend to agree. unless we have an _insanely_ bright projector it won't be of much use in a "classroom" environment where we want to have decent lighting. I'm still leaning towards LED screens...

**Comment by harrygfox** [comment]
@nelsonic @sohilpandya love the list. I'd include stationary. For my part a lot of the recent workshops I've run have been heavy on the use of paper, pens (or varying weights/thicknesses), and coloured sticky notes. I dream of catalogued draws for various sticky colours.....
