### ISSUE TITLE
how can i send a screen recording to myself from apple to microsoft?

### ISSUE THREAD

**Issue by carolrmc** [dwyl/video#15]
Having recorded a screen on my apple, how can I send it to my school pc which is microsoft?

**Comment by nelsonic** [comment]
@carolrmc great question, maybe this is something you can try doing tomorrow evening on your (_home_) Mac, and checking it on your School/Work PC on Wednesday...? 😉

**Comment by ghost** [comment]
[WeTransfer](https://wetransfer.com/) is a good solution for sending large files!
