### ISSUE TITLE
which video capture card ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/video#16]
as a learning video production company
we need to capture our tutorials in 1080p
so that all our output is "Full HD" as a _baseline_.

Which video capture card should we get to capture 1080p from laptops?

Video Capture Card Comparison: https://youtu.be/AaZ3vmJUItM

This one looks quite good: https://www.amazon.co.uk/AVerMedia-Extreme-Capture-1080p60-Latency/dp/B00YH40Y3I ?

_thoughts_?

**Comment by sohilpandya** [comment]
- Quicktime screen capture a good place to start and see if it lacks anything to start with?

**Comment by nelsonic** [comment]
@sohilpandya yes, Quicktime is great on Mac. ✅ 
We _also_ want to record the desktop on a Chromebook and Raspberry Pi which both have HDMI out. The idea being that the recording _process_ does not need to be managed on the device, but rather it can be done "_passively_" simply by putting a capture device on the HDMI-out in between the device and the "big screen" (_projector_).

**Comment by nelsonic** [comment]
Getting a **Elgato Game Capture HD60 S**: https://www.amazon.co.uk/Elgato-Capture-Stream-1080p60-PlayStation/dp/B01DRWCOGA it records at 1080p60 and USB 3/C so can be used with more "modern" computers. All our meetup/training content will be captured. ✅  ❤️  🚀 

Watch this overview/review: https://youtu.be/psF8bhyGnZM
