### ISSUE TITLE
Lighting!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/video#2]
We need _amazing_ lighting. 
@markwilliamfirth do you have time to visit our house some time in the next couple of weeks to scope out what lights we need?

**Comment by ghost** [comment]
The best and cheapest lighting is daylight! If you want to film at night you could buy a couple of softboxes, but these can be expensive.

**Comment by nelsonic** [comment]
Yeah, we're filming indoors... so...

**Comment by ghost** [comment]
So if you are unable to position yourself near a window then buying a couple of softboxes would be necessary.

**Comment by nelsonic** [comment]
@markwilliamfirth Recommendations?
Would these do the trick? http://www.amazon.co.uk/BPS-Continuous-Lighting-Softboxes-Aluminum/dp/B008N757H8

**Comment by ghost** [comment]
Yes, these look suitable.

A ring light is also a popular choice among a lot of YouTubers as it produces a 'halo effect' in the eyes. This is a stylistic choice and more common among lifestyle/beauty vloggers compared to tech videos.

**Comment by nelsonic** [comment]
That's how _noob_ I am to video, I hadn't realised that a **_Ring Light**_ was an _option_! 
http://www.fastforwardtime.co.uk/cn-r640-ringlight-for-dslr-filmmaking ...?

**Comment by ghost** [comment]
Softboxes bought
