### ISSUE TITLE
Lessons from Fridays workshop with Unbound

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/video#21]
We had a great time at the Agile workshop with Unbound, but here are some of the points I feel we need to discuss/improve upon:

**pre-workshop**
- Chromecast to be set up before the arrival of the clients.
- The table needs to be clean. (potentially have another table specifically for food)
- Camera 1 overlooking the table 
- Camera 2 for close up shots when anyone speaks
- Microphone in the middle of the desk to record the sound
- Discuss the layout of the workshop with everyone who's going to be present at the workshop. I was unaware of the schedule for the day. 

**during workshop**
- Do not roll the camera at all times, only film the key sections
  - This drains the battery on all the cameras, We ran out of juice early afternoon and missed filming some of the more interesting parts of the workshop. 😢 
- One person's role is to sit next to a camera and pan to whoever decides to speak.

**post-workshop**
- Feedback video
  - Come up with a few open-ended questions that can be asked at the end of the day
  - Again, this was slightly rushed, I am sure @markwilliamfirth got some great footage, my shots weren't up to scratch.
- Transfer all the footage over to a shared hard drive
  - @nelsonic I am thinking we can use the hard drive that you've shown me before at no. 2? Would it be possible to get access to it via the internet once we upload all the footage on it? 

**Next steps for Unbound workshop**
- What is the plan for all the footage that we've filmed on Friday? 
- Should we be coming up with a testimonial-style video for each workshop? 

The reason for this issue is that we can iron out any issues that we've encountered before the workshop on Thursday.

**Comment by nelsonic** [comment]
@sohilpandya do you still have any of the footage form the workshop? (_did you **upload** it somewhere?_)
Thanks! ✨

**Comment by nelsonic** [comment]
Sadly, lost to time ... 😢 
Always frustrating when the "hard" part of the work is done but not the follow-up. 😖 
Closing.
