### ISSUE TITLE
Green Screen (see issue #10)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/video#23]
As part of focussing on producing online learning content I _like_ the idea of super-imposing the "_instructor_" on the learning material ... the effect looks "_Professional_" (_to me..._) do you _agree_?

![image](https://cloud.githubusercontent.com/assets/194400/23494889/61bab3e0-ff0d-11e6-9585-7672754e3c7f.png)

![image](https://cloud.githubusercontent.com/assets/194400/23494697/4542f73c-ff0c-11e6-884e-d5ffe5b64e34.png)

@sohilpandya / @markwilliamfirth / @Cleop  where would be the _best_ place in QuietSpace to set up a Green Screen so we can record our tutorial videos?

I was thinking we could _paint_ the wall in the "Studio" https://github.com/dwyl/quietspace/issues/8
(_currently the shower room / storage cupboard / dumping ground_)
see: https://www.amazon.co.uk/Rosco-Chroma-Key-Green-Paint/dp/B003ZX2V8S

We'd need to spec out the lighting ... 
But I don't know if the dimensions of the room are too small ...
(_I like the idea of keeping our "Recording activities" "self contained" so the co-working space does not have lots of "stuff" lying around..._)

do we have a sufficiently "close up" lens on any of the cameras?
could we _get_ a lens that would work in that "_enclosed_" space?
Would a 1080p Fixed Focal length Web Cam be _enough_ to do a basic MVP in the room?

if not we may need to just get _portable_ screen: 
https://www.amazon.co.uk/s/ref=nb_sb_noss_1?field-keywords=green+screen

**Comment by sohilpandya** [comment]
I like the idea of being able to keep all our recording activities seperate from the co-working space. 

We really need to **clean** the Studio, once we do that we'll have a better idea of how much space we have and how we can utilise it. 

I've done a quick test and my 18mm gives us this angle in the studio:
![dsc_8314 copy](https://cloud.githubusercontent.com/assets/2305591/23503955/939a6a2c-ff35-11e6-9427-27e2317d5aa6.jpg)

I think there's enough space for a person to do a talk 😊

**Comment by iteles** [comment]
@nelsonic Does this issue supersede #10?

**Comment by nelsonic** [comment]
@iteles  thanks for reminding me that this discussion already existed... '#MyBad'
transferring the _detail_ to the older thread ... 👍

**Comment by Dannyy4343f** [comment]
You can find some [green screen video footage](https://greenscreenstock.com/) for  download here! I hope you will enjoy!
