### ISSUE TITLE
Harry's UI/UX Talk

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/video#28]
I managed to video @harrygfox do a talk about UI/UX, will post a private version of it here once it's uploaded onto YouTube. 

Let me know if it's OK, there will be no cutting just straight up on YT and private to start off with, if you give me the go ahead we can turn it public. 

ps. not the best of lighting etc, but great talk none the less.

**Comment by sohilpandya** [comment]
I'll try to make it look like Frontend masters esq videos.

**Comment by harrygfox** [comment]
@sohilpandya *gently prods* 👉 👉 👉 👉

**Comment by sohilpandya** [comment]
@harrygfox Its coming. 👁 Hold up. 😆

**Comment by sohilpandya** [comment]
Here it is https://www.youtube.com/watch?v=caYIXjB0EWA&feature=youtu.be

Took me the day to do.....

**Comment by nelsonic** [comment]
Great presentation @harrygfox & great video+edit @sohilpandya 🎉 
Is it time to invest in a decent **Lav Mic**? https://github.com/dwyl/video/issues/5#issuecomment-269859552

**Comment by sohilpandya** [comment]
Thanks @nelsonic 🎉 

I can try to dig that one out of my locker, and try it out. 👍

**Comment by nelsonic** [comment]
@sohilpandya FYI: Ordered the "Top 3" Lavalier Microphones on Amazon for us to try:
![image](https://cloud.githubusercontent.com/assets/194400/25515102/1fc618ea-2bda-11e7-85d5-6e7b05d688ab.png)
If you want to do a comparison video for your channel go for it. 
(_let me know if you need the H2n for consistent audio capture_)

**Comment by harrygfox** [comment]
Thanks so much for all the hard work editing @sohilpandya - you've done an amazing job! I can only apologise for all the times I ummed, errred, and turned my back to the camera. Next one will be much more polished with better delivery!

**Comment by sohilpandya** [comment]
This one has arrived

![7dd01fa5-563a-4543-8da3-43ad7a46e6c1](https://cloud.githubusercontent.com/assets/2305591/25615725/b8c7db88-2f30-11e7-994a-2280be2e042f.JPG)

**Comment by iteles** [comment]
@sohilpandya Can we close this issue now and deal with the lapel mics separately? 😊

**Comment by sohilpandya** [comment]
Yep, will create that one seperately once I get a video made for it. 👍
