### ISSUE TITLE
Can we use only open source software for editing our video?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/video#3]
@markwilliamfirth you mentioned today that you have experience of using [**Kdenlive**](https://kdenlive.org/) what are the disadvantages of using it vs. a closed-source video suite?

**Comment by ghost** [comment]
It's not as slick and doesn't have as many features, but Kdenlive recently updated and is meant to be a lot better. I'm also really interested in trying out Flowblade. For basic video editing you don't need anything more than Kdenlive/Flowblade. If you don't have Linux, Adobe Premier for Windows and Final Cut Pro for Mac.

**Comment by nelsonic** [comment]
We _have_ final cut, but would _prefer_ to use open-source tools where ever _possible_.

**Comment by ghost** [comment]
Well Final Cut is very intuitive and easy to pick up, but for open source Kdenlive/Flowblade (Linux).

**Comment by nelsonic** [comment]
Ok. Lets just start and see what works. thanks @markwilliamfirth :+1:
