### ISSUE TITLE
Tripod

### ISSUE THREAD

**Issue by nelsonic** [dwyl/video#4]
@iteles do we still have a Tripod @dwyl **HQ** ?
If not, @markwilliamfirth what would you recommend?

**Comment by ghost** [comment]
I have a http://www.sony.co.uk/electronics/cyber-shot-compact-cameras-tripods-remotes/vct-r100
because it is good for portability, but a tripod is a tripod you could use a stack of books if you wanted to! If you're going to invest in one, just make sure it's not too cheap and the right height (the one I have linked above isn't tall enough for shooting whilst the subject is standing with the tripod on the ground).

**Comment by nelsonic** [comment]
We used to have a manfrotto compact but sadly it died this summer... so I was _considering_ replacing it with: http://www.manfrotto.co.uk/compact-action-black-tripod which extends fully to **155 cm**
I don't know enough about tripods to differentiate between this and anything "better"...

**Comment by ghost** [comment]
There is not really much to know about tripods. The main issues to consider when buying one is the portability/weight/height/cost. A taller tripod will be heaver and less portable. A cheaper tripod will not be as sturdy. If it extends to 155cm then it will not be suitable for filming whilst standing, unless you can stand the tripod on something else.

If you plan on filming whilst sitting / doing interviews this isn't an issue.

**Comment by nelsonic** [comment]
@markwilliamfirth is the unsuitability for filming while standing due to wanting to have the camera lens at eye-level?

**Comment by ghost** [comment]
Exactly! Sorry if I wasn't clear enough.

**Comment by nelsonic** [comment]
Ok. so should the full extension be like 200cm ?

**Comment by iteles** [comment]
@nelsonic We have a very decent Manfrotto tripod that is tall enough for eye level and pretty solid. I also have two different swivel heads for it that were passed down to me by an avid photographer so I think we're covered. 

I'll show you which one it is @markwilliamfirth and you can check it's ok! :blush:

**Comment by nelsonic** [comment]
Cool. so we can close this for now. thanks @iteles & @markwilliamfirth :+1:

**Comment by nelsonic** [comment]
@iteles did you fetch the tripod from storage (_or is it on your list_...?) _thanks_! :+1:

**Comment by iteles** [comment]
@nelsonic It's not done. Completely accessible (just not in the way). :+1:
