### ISSUE TITLE
dwyl Intro Video for FAC

### ISSUE THREAD

**Issue by rub1e** [dwyl/video#44]
FAC invites everyone to come and introduce 🤝  themselves / their company to new cohorts, and obviously _dwyl_ should have pride 🦁 🦁 of place as FAC's most important and long-standing partner.

Since this is going to happen three times a year (or more depending on growth), it might be a nice idea for out-of-towners @iteles and @nelsonic to record a short video 🎥  introducing themselves, their vision for dwyl 👁‍🗨 , and their history with FAC. (Which we can then reuse)

We'll be doing our intro session on 7th November (to be confirmed), so if you guys fancy it, you have until then.

I'll let you two decide what `priority` to give this...

**Comment by rub1e** [comment]
An immigrant from https://github.com/dwyl/hq/issues/501, this issue was told by the people of HQ that it just didn't belong :crying_cat_face:

**Comment by iteles** [comment]
We did this in person in the end and doing on for FAC is no longer relevant. 
Further issues to be opened on dwyl intro videos that are more current 👍
