### ISSUE TITLE
Which Camera Lens for Indoor Interview/Tutorial Videos?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/video#48]
Thinking of getting a wide(r) angle lens with larger aperture for shooting indoors and in low-light. 
My reasoning for getting a better quality lens is to _minimise_ noise and maximise low-light quality.

[![image](https://user-images.githubusercontent.com/194400/48966989-1cca7100-efd2-11e8-8d67-2e15e03d2185.png)](https://youtu.be/1kAVGQvYGEw)
https://youtu.be/1kAVGQvYGEw

Comparison video "Canon 24mm STM Pancake vs 40mm STM Pancake vs 50mm 1.8"
[![image](https://user-images.githubusercontent.com/194400/48962105-55872d80-ef73-11e8-816e-7f8f2e70455d.png)](https://youtu.be/Bj0CmBfU6M4)

# Canon EF 24mm f/1.4L II USM Lens

While searching for the lens I discovered that MKBHD had done a review of it _way_ back in the day!
[![image](https://user-images.githubusercontent.com/194400/48960625-fa027300-ef65-11e8-8d94-6847eabe6a94.png)](https://youtu.be/LpC6UwZR_Hw)
https://youtu.be/LpC6UwZR_Hw
Back when he was using a Canon T2i ... 😮
He's come a _long_ way from these humble beginnings! 🚀 

[![image](https://user-images.githubusercontent.com/194400/48960698-da1f7f00-ef66-11e8-9ac1-838fa846bea0.png)](https://youtu.be/DiIYLgo62kU)
https://youtu.be/DiIYLgo62kU

The "normal" price of this lens is **$1,549** (USD) from B&H in NYC:
https://www.bhphotovideo.com/c/product/590449-USA/Canon_2750B002_EF_24mm_f_1_4L_II.html
![image](https://user-images.githubusercontent.com/194400/48961915-bbbe8100-ef70-11e8-90bf-7ebbea8e7286.png)

In Portugal this lens costs **€1,464** (_"Black Friday" deal_):
https://www.fnac.pt/Canon-Objetiva-EF-24mm-f-1-4L-II-USM-Objectiva-Objetiva-para-Canon/a687243
![image](https://user-images.githubusercontent.com/194400/48960922-a6ddef80-ef68-11e8-82b8-bc427689aa20.png)

Found it on **ebay** for **£945** ("_Ex display, in great condition comes with caps_"):
https://www.ebay.co.uk/itm/Canon-EF-24mm-f-1-4L-II-USM-Lens/283255637116
![image](https://user-images.githubusercontent.com/194400/48961936-e27cb780-ef70-11e8-86dd-8b36ba33a4a8.png)
I'm _very_ tempted to "buy-it-now" on this because it's a _good_ deal! 

I always find it _bonkers_ that lenses costs more than many _decent_ cameras, but there is no getting around this, _all_ "_serious_" photographers/videographers _invest_ in their "glass". 

If you're following along wondering what these numbers mean, 
see: https://expertphotography.com/what-do-the-numbers-and-letters-on-lenses-mean

+ **f/1.4** means that it has a wide aperture. (_this the main number I'm interested in for low-light_) https://en.wikipedia.org/wiki/Aperture#Maximum_and_minimum_apertures
+ **24mm** is the "focal length". this is what determines how close you can be to the subject being captured. The _best_ Canon lens has a 10mm focal length. 

# Relevant Background Reading

+ What is the Difference Between Canon EF and EF-S Lenses?
https://www.photographybay.com/2014/02/23/what-is-the-difference-between-canon-ef-and-ef-s-lenses/
> Canon EF-S lenses are designed solely for use on Canon APS-C DSLRs. Canon EF lenses are designed to work with full frame and APS-C DSLRs from Canon. i.e. EF-S will only work on 80D, 7D etc.  but an EF lens will work on _any_ Canon DSLR. So the _smart_ choice of lens is an **EF**.

**Comment by iteles** [comment]
I don't know if you found the wide angle lens we own when you went searching for it but it may well be in a different box to the camera bag because the wide-angle had its own carrying case. 

I have asked 'the man who knows' if he remembers the spec off-hand.

**Comment by nelsonic** [comment]
@iteles the lens you are referring to is actually a Fisheye converter. I looked for it, but didn't find it.

**Comment by nelsonic** [comment]
Picked up the Canon **24mm F1.4 L** II Ultrasonic Lens:
https://www.fnac.pt/Canon-Objetiva-EF-24mm-f-1-4L-II-USM-Objectiva-Objetiva-para-Canon/a687243
![image](https://user-images.githubusercontent.com/194400/49097759-5f57ac00-f265-11e8-8e33-5667872b8046.png)

For _considerably_ less than half the RRP:
![image](https://user-images.githubusercontent.com/194400/49097932-b5c4ea80-f265-11e8-8e28-e8350835a664.png)

Looking forward to trying it out with @iteles 7D and the Sony A7 with lens adapter. 😉 

![image](https://user-images.githubusercontent.com/194400/49098863-cfffc800-f267-11e8-8984-61385011a840.png)
