### ISSUE TITLE
Sony Mirrorless Full Frame Camera for Video

### ISSUE THREAD

**Issue by nelsonic** [dwyl/video#49]
I have been researching which camera to use as my "A" video camera so that I/we can level-up my/our video game. The "**tl;dr**" is: I'm buying a **Sony A7 III** + Lenses with my _own_ cash and will make it available to anyone **`else`** [@home](https://github.com/dwyl/home) who wants to use it for stills/video. 

# _Why_?

**Storytelling** with ***video*** is the **21st century** equivalent of **literacy** (_ready & writing_).
I feel that it should be integral part of the _primary_ school creative visual arts curriculum
and **_everyone_ should learn** how to produce **video**.  I _firmly_ believe that being able to _capture_, condense and share video makes the **World** a "**_better_ place**". It helps us to share our _own_ ideas and to _empathise_ with people with whom we share very little in common day-to-day. 

[![argentina_flood](https://user-images.githubusercontent.com/194400/48977011-b739bb80-f089-11e8-9239-33a865c6c650.jpg)](https://www.wunderground.com/blog/JeffMasters/earths-record-41-billiondollar-weather-disasters-of-2013.html "Floods in Argentina")

The "everyone should learn to code" quote from Steve Jobs is often repeated:

![image](https://user-images.githubusercontent.com/194400/48976870-991e8c00-f086-11e8-955e-20eb92ca9247.png)
I feel that a _similar_ quote/mindset applies to video:

# "_Everyone_ should learn how to create `video` because it teaches you how to _communicate_"

My [_personal_ learning objective](https://github.com/dwyl/hq/issues/497) for the next year of my life is to capture _all_ of my DIY/Furniture projects for [@home](https://github.com/dwyl/home). I will be sharing as many of the project plans as possible as "Open Source" which will be _useful_ to other people who want to build their _own_ furniture, kitchens, home office, etc. 💡 

# What? 

Having a ~~good~~ _great_ camera is the _first_ step in the journey to ~~good~~ _great_ video.
No amount of "post production" work can repair a poor image so I feel it makes sense to start with the _best_ sensor I can _afford_. 

> _Yes, there are plenty of people making videos on their smart phones, and that works well in many situations, but I want something I can use in low-light and with more fine-grained control than a typical smart phone - even an iPhone XS or Pixel 3. I also want "professional" workflow beyond what a phone offers ... I'm still going to use my iPhone SE to capture video without a doubt! I just want to have an "**A Game**" camera  I can use for the **highest possible quality**._

Last year I bought the **Canon G7X MKII** and it's been _excellent_ for for _personal_ video 
(_which I've accumulated around **4TB** ... a full [Lacie Rugged Drive](https://www.lacie.com/gb/en/products/rugged/) ...  in the past year!_) 
see: https://github.com/edwardcodes/Around-the-World/issues/9

> I haven't _uploaded_ any of the videos because I have no intention of doing a (_personal_) "**Vlog**". 
I'm not "knocking" Vlogs, they have their place, I just don't think _my_ life is that "_interesting_" (_to other people_) and don't want to _waste_ anyone _else's_ time with my personal "home movies". 

While I don't feel that I've "outgrown" the G7X MK II in terms of my _abilities_ as an _amateur_, 
I feel that I want to push myself to _learn_ how to be a professional using the equipment people making videos for a _living_ are using. Ultimately, I want the quality of my video to be good enough that I can become a **_professional_ videographer**. 

## Does (Camera Sensor) Size _Matter_?

 

Benjamin Jaworskyj has a good video on this: (_it's a bit protracted but goes into decent detail ..._) 
[![image](https://user-images.githubusercontent.com/194400/48977422-bd339a80-f091-11e8-99a4-049398a1d793.png)](https://youtu.be/UnLyg7TZEuY)
https://youtu.be/UnLyg7TZEuY

After asking Google "**Which DSLR/Mirrorless for video**?" and reading **Borrow Lenses** insightful comparison https://www.borrowlenses.com/blog/best-dslr-for-video into DSLR (Canon/Nikon) and Mirrorless Full Frame (Sony), I went down a "rabbit hole" of looking at Canon Cameras ... 🔍⏳ 

I considered getting a **Canon 5D MK IV**, but it was heavy, (_comparatively_) slow, has a **_fixed_ screen** and **crops video** at 4K (_which means it's basically **useless** for **4K** video_)! ✂️ 

My next line of enquiry was **Canon 6D MK II** which looked much better (_fold-out-screen_) but suffers from poor "edge" auto-focus, reduced dynamic range and "only" does 1080p @ 30FPS 🙄 
see Jared Polin's real-world review: https://youtu.be/1Po4Ct8B2Oo ... 

Next I looked at the **Canon XC10/15** as a _dedicated_ Video device, but the **1" sensor** is _much_ too "weak" considering the price! see: https://www.dpreview.com/reviews/crossing-the-bridge-canon-xc10-review
(_it doesn't have that much more to offer over my G7X MKII which is much more compact/versatile!_)

One of my biggest "gripes" with @iteles' **Canon 7D** is the "jackhammer" mechanical shutter sound!
Not that I have any intention of taking pictures where I'm not supposed to (_e.g. museums_),
just that I find it *super* annoying to her the "clack" of DSLR shutters! 
My _other_ biggest issues with the **7D** are the (_relatively_) "slow" auto-focus and if you are using an **_external_ Microphone** (_and are recording in-doors_) it will pickup the [**noise** of the AF motor](https://photography-on-the.net/forum/showthread.php?t=871491). 😞 

Long-story short, my reasoning for considering going ***mirrorless*** is to **_eliminate_ shutter noise**!!

So my _next_ line of enquiry was the Panasonic Lumix **DC-GH5** Mirrorless Micro Four Thirds 
which looks _really_ good! https://github.com/dwyl/video/issues/1#issuecomment-277609463

The Amazon (UK) price for the **GH5** with LEICA 12-60 mm Lens is **£1,665.85** + VAT
(_luckily we have a biz that is registered for VAT so we could claim that back_)
https://smile.amazon.co.uk/Panasonic-DC-GH5LEB-K-Compact-System-Camera/dp/B01MT7AK63/
![image](https://user-images.githubusercontent.com/194400/48969280-8ce9ee80-eff4-11e8-9256-78c7f68c1e93.png)
Also, Panasonic UK has a Promo which would have given a further **£250** of **discount** ("cash back")!
https://smile.amazon.co.uk/b/ref=dp_wintercashback?node=15909708031
![image](https://user-images.githubusercontent.com/194400/48969553-236bdf00-eff8-11e8-9408-a72d65adb626.png)
Specifically the _second_ item in the cashback table:
![image](https://user-images.githubusercontent.com/194400/48969585-92493800-eff8-11e8-98ca-7aa2ec4417df.png)

So this idea was **_immensely_ appealing** to me ... 
the GH5 is an _amazing_ camera with _many_ pro video features!

So ... I kept watching review videos, _especially_ "long term" reviews such as this one
from _super_ popular professional Vlog/Videographers **Tony & Chelsea Northrup**: 
**Panasonic GH5 _Long-term_ Review (2018): A YouTuber's _Workhorse_**
[![image](https://user-images.githubusercontent.com/194400/48969611-ca507b00-eff8-11e8-8b9a-e88e2b1d1cf1.png)](https://youtu.be/73vBlRjauDI)
https://youtu.be/73vBlRjauDI

In the video Tony describes how having **4K 60p** is _useful_ for "run-and-gun" style shooting.
Because shooting in 4K means they can _crop_ the video in "post" and remove anything they don't want and can do "in-camera cuts" by zooming in (_again in post_) giving the "two camera" effect.
I _understand_ this mindset on the _surface_. But **_storing_ 4k 60p** video _obliterates_ hard drives and take _much_ longer to edit/render! I don't think I would use it. 

### GH5 _Autofocusing_ ... 😞 

"I cannot recommend the GH5 for people who are going to film themselves ..." [3:13](https://youtu.be/73vBlRjauDI?t=193)

At this point is was "back to the drawing board" in terms of the **GH5**. 
So now my only _realistic_ option is _Sony_!

# Sony A7 Series (_Mirrorless Full Frame_) 

This was the most _insightful_ introductory article I read on the subject:
https://www.digitaltrends.com/photography/best-sony-a7-series-camera
which A7 model should I get? https://camerajabber.com/which-sony-a7-camera (May 2018)

Faruk Korkmaz (iPhonedo) did a _superb_ intro/review for the **A7 III**:
[![image](https://user-images.githubusercontent.com/194400/48968417-65405980-efe7-11e8-8467-515c921ac0c3.png)](https://youtu.be/5IQ6uk1e8-g)
https://youtu.be/5IQ6uk1e8-g
In this video Faruk _starts_ by saying that he _returned_ his **GH5** because of the autofocus 
and is _delighted_ by the **A7 III** for Autofocus, Low-light and Video Quality. 🎉 
(_we're off to a good start!_)

## A7S II or A7 III ?

@sohilpandya _first_ recommended/suggested the A7S II in https://github.com/dwyl/video/issues/1#issuecomment-277643497 (_last year_)
https://www.sony.co.uk/electronics/interchangeable-lens-cameras/ilce-7sm2
![image](https://user-images.githubusercontent.com/194400/48969711-629b2f80-effa-11e8-8cf0-b06c8002f794.png)

![image](https://user-images.githubusercontent.com/194400/48969730-a42bda80-effa-11e8-9a18-873a1a49df43.png)

"Ultra-high sensitivity, extra-wide dynamic range and improved image processing algorithm deliver high-quality images with spectacular details."

Comparison between the two modes I am _considering_:
[![image](https://user-images.githubusercontent.com/194400/48969261-51e7bb00-eff4-11e8-8d66-8a1894bde315.png)](https://youtu.be/9YIMkJbxrGU)
https://youtu.be/9YIMkJbxrGU

[Philip Bloom](https://main.philipbloom.net/about)'s a7S Seminar is super insightful on the capabilities of the camera for film-making:
[![image](https://user-images.githubusercontent.com/194400/48969188-303a0400-eff3-11e8-9453-1bd389dac058.png)](https://youtu.be/zeX-eZXaRtw)
https://youtu.be/zeX-eZXaRtw

![image](https://user-images.githubusercontent.com/194400/48969169-dfc2a680-eff2-11e8-8103-c4fffc089459.png)

## Sony A7iii Design Features/Improvements

This is a good video summary of why the **Sony A7iii** is _better_ than previous models (_including A7SII_)

![image](https://user-images.githubusercontent.com/194400/48976774-003b4100-f085-11e8-8bf2-121836276490.png)

## EISA Named the A7 III Camera of the _Year_ 2018-2019

When viewing the _official_ product page on the Sony website, it's noted that the A7 III was named as 
"**Camera of the _Year_ 2018-2019**" by EISA (_Expert Imaging and Sound Association_).
EISA is a consortium of professional multimedia (photo/video/sound) magazines, they are _experts_.
https://www.sony.com/electronics/interchangeable-lens-cameras/ilce-7m3-body-kit
![image](https://user-images.githubusercontent.com/194400/48977551-58c60a80-f094-11e8-8bf9-3c1d098fcbf4.png)
![image](https://user-images.githubusercontent.com/194400/48977566-b65a5700-f094-11e8-8255-afcbd3133240.png)

Read more: https://www.eisa.eu/awards/sony-a7-iii

## Can I use a Canon Lens with a Sony A7{x} Camera?

The _obvious_ next question when considering an interchangeable lens camera is:
+ Can I use my _existing_ lenses? (_or if you are completely new to this ..._)
+ Can I use _reasonably_ priced high quality lenses with the Sony A7 range?

To which the answer is ***Yes***! 🎉 

Read: https://briansmith.com/sony-a7-a7r-lens-mount-adapters/
Short answer: yes! It's possible to use Canon EF lenses on Sony A7 Cameras 
using a _reasonably_ cheap adapter:

[![image](https://user-images.githubusercontent.com/194400/48968537-cd436f80-efe8-11e8-8d7f-617e65afa032.png)](https://youtu.be/jFdppCfLbcQ)
https://youtu.be/jFdppCfLbcQ

**Brandon Li** advises _against_ using Canon Lenses with the Metabones EF to E-mount:
[![image](https://user-images.githubusercontent.com/194400/48971458-e6144b00-f011-11e8-86a9-09d9ff2cb6ff.png)](https://youtu.be/H7m9rpp-dYw)
https://youtu.be/H7m9rpp-dYw
Says that the Autofocus was inconsistent with the Canon lens... 😕 
This is _not_ going to affect me because I will be investing in the Sony "G" and Zeiss lenses, (_see below_)
but it's good to know that I can use Inês' 100-400mm Telephoto lens if I ever want/need to.

## Sony or Zeiss Lens?

Zeiss 16-70mm vs Sony 18-105 G Lens Comparison
[![image](https://user-images.githubusercontent.com/194400/48971655-89fef600-f014-11e8-8e51-46c69c029cd3.png)](https://youtu.be/hiVYb-960QU)
https://youtu.be/hiVYb-960QU

### Sony FE 28-70mm Lens Review - A Great Kit Lens For Only $200

[![image](https://user-images.githubusercontent.com/194400/48976437-a421ee00-f07f-11e8-9f20-c1360df8e80c.png)](https://youtu.be/KP2ZVI8scjs)
https://youtu.be/KP2ZVI8scjs

## Counter Arguments _Against_ the Sony Mirrorless System

https://petapixel.com/2016/04/04/sonys-full-frame-pro-mirrorless-fatal-mistake
makes a few valid points but is mostly based on out-dated data about "older" Sony models.
good rebuttal: https://petapixel.com/2016/04/05/defense-sonys-pro-mirrorless-cameras

_Ultimately_ the autofocus on the A7 III and A9 is _insanely_ good (_much better than the equivalent Canon/Panasonic_) and the camera size/weight argument is _irrelevant_ to me. 
What _matters_ to me is the quality of the photo/video and the elimination of shutter noise.

**Comment by nelsonic** [comment]
Guide to A7 Lens Adapters: https://briansmith.com/sony-a7-a7r-lens-mount-adapters/

**Comment by nelsonic** [comment]
# Price Research

RRP: **$1,999.99** (Body) ***$2,199.99*** (Body + 28-70 mm Zoom Lens) 
https://www.sony.com/electronics/interchangeable-lens-cameras/ilce-7m3-body-kit
![sony-rrp](https://user-images.githubusercontent.com/194400/49000371-3b0aab00-f151-11e8-9086-48cacd7d23e7.png)

The Amazon (UK) price (body only) is **£1,899**:
https://www.amazon.co.uk/d/Compact-Cameras/Sony-ILCE7M3KB-CEC-Mirrorless-Compact-SEL2870/B07B4L1PQ8/
![image](https://user-images.githubusercontent.com/194400/48999571-f41bb600-f14e-11e8-8df2-81517ac1a021.png)

Fnac (PT) price (body only) is **€2300**:
https://www.fnac.pt/Sony-Alpha-%CE%B17-Mark-III-Corpo-Camara-Fotografica-Digital-Camara-CSC-Mirrorless/a1614520
![image](https://user-images.githubusercontent.com/194400/48999728-69878680-f14f-11e8-934f-e80ff768033d.png)

The only reason I would _consider_ buying it from a _physical_ retailer would be for an extended warrantee ... 🤔 (_this has worked out well in the past when cameras have accidentally gone swimming!_)

## Best Price on Ebay

https://www.ebay.co.uk/itm/UK-Sony-Alpha-a7-III-Mirrorless-Digital-Camera-Body-Only/183192214453
![image](https://user-images.githubusercontent.com/194400/48999018-3643f800-f14d-11e8-8094-7e24260cda71.png)

Kit with a _basic_ **Sony FE 28-70mm f/3.5**-5.6 OSS Lens:
![image](https://user-images.githubusercontent.com/194400/48998785-8078a980-f14c-11e8-9f6c-0d2ea504faef.png)

This lens by itself is **$398**:
https://www.bhphotovideo.com/c/product/1015472-REG/sony_sel2870_fe_28_70mm_f_3_5_5_6_oss.html
![image](https://user-images.githubusercontent.com/194400/49009475-94ca9f80-f168-11e8-99fa-57fd383598bd.png)
But if I were to go on "_holiday_" with this setup, I would probably only take the **24mm f1.4 G** (_see below_),
so I feel it might be a bit "redundant" ... (_it might not get much use ..._)


The ebay seller " https://www.ebay.co.uk/usr/60roadebut seems legit (_enough positive feedback_):
![image](https://user-images.githubusercontent.com/194400/48999282-1234e680-f14e-11e8-992a-a28128db7bea.png)



# Lenses? 

_Obviously_ I would _like_ to get the _best_ lenses available, but they are _**obscenely expensive**_!! 😞
This is a good post on Lenses for the A7 series: 
https://www.slrlounge.com/first-5-lenses-buy-sony-a7-series-camera
The article was published in 2016 and a _lot_ has happened (_been released_) since then.

These are the lenses I would _like_ get in the _order_ I would buy them:

### Sony FE 24mm f/1.4 GM Lens 

This is _perfect_ lens for close-up and ***low-light***. It has a focal distance of 24cm.

https://www.bhphotovideo.com/c/product/1435887-REG/sony_fe_24mm_f_1_4_gm.html
![image](https://user-images.githubusercontent.com/194400/49003705-65149b00-f15a-11e8-9109-63c877d98b0f.png)

### Reviews:

[![image](https://user-images.githubusercontent.com/194400/49003846-bb81d980-f15a-11e8-90e0-071c0ab75dda.png)](https://youtu.be/aW-xRCrZXIc)
https://youtu.be/aW-xRCrZXIc

[![image](https://user-images.githubusercontent.com/194400/49005891-c428de80-f15f-11e8-9bd9-925313ecbf7b.png)](https://youtu.be/CBrVKfEhjZU)
https://youtu.be/CBrVKfEhjZU

[![image](https://user-images.githubusercontent.com/194400/49004852-30561300-f15d-11e8-80ed-09cc408fc3e8.png)](https://youtu.be/SSf7Z-yp6xU)
https://youtu.be/SSf7Z-yp6xU

[![image](https://user-images.githubusercontent.com/194400/49009154-b8d9b100-f167-11e8-964f-93a70cd20b86.png)](https://youtu.be/DM2otwnuiTE)
https://youtu.be/DM2otwnuiTE

This is the review that shows the most ***Video*** taken with the lens and the A7 III:
![image](https://user-images.githubusercontent.com/194400/49009230-f4747b00-f167-11e8-8dc3-f3e984e12607.png)
I must say, I agree wholeheartedly with this. If I could _only_ have ***one*** lens, this would be it!
iPhonedo summarises my thoughts on this:
![image](https://user-images.githubusercontent.com/194400/49011145-5d122680-f16d-11e8-8027-41b63df8bbb1.png)


[![image](https://user-images.githubusercontent.com/194400/49011043-f5f47200-f16c-11e8-991e-7cac8a8096c7.png)](https://youtu.be/HNXM9MDR-8I)
https://youtu.be/HNXM9MDR-8I
Max compares the 28mm F2.0 (Tamron) lens to the Sony 24mm/F1.4, it's a **_noticeable_ difference**.

Jason literally describes this lens as a "_dream come true_" ...
[![image](https://user-images.githubusercontent.com/194400/49011821-5d132600-f16f-11e8-842b-28f24fec19cd.png)](https://youtu.be/hX7m_XpgCdI)
https://youtu.be/hX7m_XpgCdI

#### Best Price: £1,289 (£1,269 + £20.00 postage)

https://www.ebay.co.uk/itm/UK-Sony-FE-24mm-f-1-4-GM-Lens-SEL24F14GM/183488873855
![image](https://user-images.githubusercontent.com/194400/49004168-99d52200-f15b-11e8-9e22-e4769e381f5a.png)


#### With UK Seller Warranty: £1,370 (£1,359.99 + £20 postage)

https://www.ebay.co.uk/itm/Brand-New-Sony-FE-24mm-f-1-4-GM-G-Master-Lens-SEL24F14GM-3-Year-Warranty/163326773867
![image](https://user-images.githubusercontent.com/194400/49003923-f84dd080-f15a-11e8-93d1-211733532238.png)

### Sony FE 28mm f/2 (_budget friendly option_)

https://www.bhphotovideo.com/c/product/1126139-REG/sony_sel28f20_fe_28mm_f_2_lens.html
![image](https://user-images.githubusercontent.com/194400/49008447-c1c98300-f165-11e8-8bbb-9a6e2a70c034.png)

[![image](https://user-images.githubusercontent.com/194400/49008626-2edd1880-f166-11e8-9165-c006bf3742c7.png)](https://youtu.be/CRoc52dy_-g)
https://youtu.be/CRoc52dy_-g

https://www.fnac.pt/Objetiva-Sony-FE-28mm-f-2-Objectiva-Objetiva-para-Sony/a4506156
![image](https://user-images.githubusercontent.com/194400/49008362-9050b780-f165-11e8-9e98-babdbf13d9b0.png)


### Sony FE 12-24mm f/4 G Lens
https://www.bhphotovideo.com/c/product/1338517-REG/sony_sel1224g_fe_12_24mm_f_4_g.html
![image](https://user-images.githubusercontent.com/194400/48999072-6ab7b400-f14d-11e8-8c2f-ded7276ce8e9.png)

#### Sony FE 12-24 F/4 G Lens Review
[![image](https://user-images.githubusercontent.com/194400/49000228-cdf71580-f150-11e8-91ff-3cac5605aa26.png)](https://youtu.be/CBSiaGvLX9c)
https://youtu.be/CBSiaGvLX9c - the review is _fairly_ factual, but Mark Galer is a "Sony Ambassador" ... 🙄 

Cheapest I found online was _again_ on eBay:
https://www.ebay.co.uk/itm/UK-Sony-FE-12-24mm-f-4-G-Lens-Full-Frame-E-Mount-SEL1224G/183042488296
![image](https://user-images.githubusercontent.com/194400/48998915-ecf3a880-f14c-11e8-9d3c-a6edc781fb15.png)


### Sony FE 24-240mm f/3.5-6.3 OSS Lens

https://www.ebay.co.uk/itm/NEW-Sony-FE-24-240mm-f-3-5-6-3-OSS-Lens-F3-5-6-3-SEL24240/183308496357
![image](https://user-images.githubusercontent.com/194400/49004337-fa645f00-f15b-11e8-9aa2-1e0805ded993.png)

### Sony Vario-Tessar T* E 16-70mm F4 

https://www.ebay.co.uk/itm/UK-Sony-Vario-Tessar-T-E-16-70mm-F4-ZA-OSS-E-mount-Lens-SEL1670Z/183042488520
![image](https://user-images.githubusercontent.com/194400/48998960-0dbbfe00-f14d-11e8-9abf-c0b293b86f89.png)


## 3<sup>rd</sup> Party Lenses (_budget_)

### Samyang 12mm F2.0 

€259,99 on Fnac (eGlobalCentral) https://www.fnac.pt/mp11958759/Objectiva-Samyang-12mm-F2-0-NCS-CS-para-Sony-E-Mount-APS-C-Preto
![image](https://user-images.githubusercontent.com/194400/49006567-4c5bb380-f161-11e8-8bf2-f1da58a09dd9.png)

Direct: https://www.eglobalcentral.eu/samyang-12mm-f2.0-ncs-cs-lens-for-sony-e-mount-with-hoya-67mm-filter-black.html
![image](https://user-images.githubusercontent.com/194400/49006655-7a40f800-f161-11e8-8e6f-f649f83d84ed.png)

Video review: https://youtu.be/y7XiuV_u8XE

# But _First_ ...

Before spending a _ton_ of cash on the _really_ nice Sony G lens, I'm going to get an _adapter_
to _try_ using the Canon glass @iteles _already_ has ... 

[![image](https://user-images.githubusercontent.com/194400/49021756-44b10480-f18b-11e8-986d-74afc18614ac.png)](https://youtu.be/b_dVkZasTCI)
https://youtu.be/b_dVkZasTCI

[![image](https://user-images.githubusercontent.com/194400/49022547-06b4e000-f18d-11e8-8dff-ba41669dd2b0.png)](https://youtu.be/_FVCHHRD7Y8)
https://youtu.be/_FVCHHRD7Y8

Sigma appears to be the adapter that works best with face/eye autofocus:
![image](https://user-images.githubusercontent.com/194400/49022937-fa7d5280-f18d-11e8-879a-381bb6956211.png)

Price in Portugal:
![image](https://user-images.githubusercontent.com/194400/49023000-23054c80-f18e-11e8-94b7-9f75ab7e8e43.png)

Best available price on eBay:
https://www.ebay.co.uk/itm/Sigma-MC-11-Mount-Converter-Canon-EOS-to-Sony-E-Mount-Adapter/253980887040
![image](https://user-images.githubusercontent.com/194400/49021545-c48a9f00-f18a-11e8-8612-dd1efd5b1e37.png)

Ordered it:
![image](https://user-images.githubusercontent.com/194400/49021818-67dbb400-f18b-11e8-9caa-3ffe33a18e19.png)

I'm _also bidding_ on a **Metabones MK V** on ebay. Not expecting to win it ... The RRP is $450 🙄 
Reviews aren't _amazing_ for _continuous_ autofocus ... going with the Sigma MC-11 because Inês has two EF Sigma lenses which I want to try ... 🤞

**Comment by nelsonic** [comment]
# Sigma 20mm F1.4 DG HSM Art Lens

Jason's review is _specific_ to video continuous **autofocus**: 
[![image](https://user-images.githubusercontent.com/194400/49041483-3ed41700-f1bd-11e8-94d1-3d338ee34d12.png)](https://youtu.be/5H06Ir_zOmM)
https://youtu.be/5H06Ir_zOmM

Conclusion: Sony G or Seiss lenses are better for video autofocus. 

https://www.ebay.co.uk/itm/Sigma-20mm-F1-4-DG-HSM-Art-Lens-for-Sony-E-FE-Mount-UK-Stock-BNIB/123392534140
![image](https://user-images.githubusercontent.com/194400/49041358-f3216d80-f1bc-11e8-96db-97ff99d37356.png)

**Comment by nelsonic** [comment]
[![image](https://user-images.githubusercontent.com/194400/49042123-12b99580-f1bf-11e8-8a62-07bd71ec794f.png)](https://youtu.be/ED5FJ_FIHb4)
https://youtu.be/ED5FJ_FIHb4


[![image](https://user-images.githubusercontent.com/194400/49041972-adfe3b00-f1be-11e8-9603-6d65116fbe30.png)](https://youtu.be/QA06SIXRBMI)
https://youtu.be/QA06SIXRBMI

[![image](https://user-images.githubusercontent.com/194400/49042220-69bf6a80-f1bf-11e8-8869-8ace5794ed76.png)](https://youtu.be/-qgcbK96_2U)
https://youtu.be/-qgcbK96_2U
"super fast autofocus"  using Sony A7R III

https://www.ebay.co.uk/itm/Sigma-16mm-F1-4-DC-DN-Contemporary-Lens-in-Sony-E-Fit/192387250680
![image](https://user-images.githubusercontent.com/194400/49042384-f407ce80-f1bf-11e8-882d-47c39346c151.png)

Cody Blue discusses the use of APS-C (crop) Lens on a Full Frame camera:
[![image](https://user-images.githubusercontent.com/194400/49042546-5bbe1980-f1c0-11e8-92a8-537fbc59db9a.png)](https://youtu.be/6oFRP4ZQADY)
https://youtu.be/6oFRP4ZQADY

Conclusion: if you're going to invest in a full frame camera, you should invest in full frame glass.

**Comment by iteles** [comment]
This is the mother of all scrollable issues 😄 

Good shout on the adapter :+1: You'll probably end up with a Sigma lens from all the research, but good to try it out seeing as we have access to quite a few Canon lenses.

**Comment by nelsonic** [comment]
https://cameradecision.com/compare/Canon-EOS-6D-Mark-II-vs-Sony-Alpha-A7-III
![image](https://user-images.githubusercontent.com/194400/49099186-bf9c1d00-f268-11e8-8453-4b40d6e1ba5a.png)

Perhaps it's best to consider the _use-case_: **_indoor_ video** capture at **1080p 25fps**.
For that use the Canon 6D Mk II is _better_ than the Sony because the colors are richer (_less time color grading_) and the Autofocus is (_supposedly_) faster during _video_ recording.

## 7 Reasons to consider the Canon 6D MK II instead of Sony A7 III

[![image](https://user-images.githubusercontent.com/194400/49099778-338af500-f26a-11e8-941c-d80fbfa6eaf2.png)](https://youtu.be/OwMfpzix14Y)
https://youtu.be/OwMfpzix14Y

1. **Fully articulating screen** (_front-facing_).
2. Color Science is more "natural". (_Sony is more "harsh" in the same lighting conditions_) 
![image](https://user-images.githubusercontent.com/194400/49099951-b0b66a00-f26a-11e8-955d-8ac23afa174c.png)
3. Price (_the canon is quite a lot cheaper and the Lenses are **much cheaper** too_) 
4. Highest quality lenses are cheaper on Canon. see: https://github.com/dwyl/video/issues/48#issuecomment-442136591
5. Video stabilisation ... (_this is dubious ... but I'd say that it's *irrelevant* for tripod video_) 
  but he does note that Sony's "cropped" video stabilisation is good, but not 
6. _Smoother_ & _continuous_ video "dual pixel" autofocus. (_only relevant for moving subjects_)
[![image](https://user-images.githubusercontent.com/194400/49100505-050e1980-f26c-11e8-9eda-fbc86c0bc7c6.png)](https://youtu.be/T3YfRqGZ6C4)
https://youtu.be/T3YfRqGZ6C4
7. **4k Timelapse** built in. No App required. (_this is unavailable on the Sony!_)
Sony _removed_ the Timelapse functionality from their "free" App. 
see: https://photorec.tv/2018/01/sony-a7riii-a9-time-lapse-options and https://youtu.be/I0D6PM9ZZzI
![image](https://user-images.githubusercontent.com/194400/49101770-ea896f80-f26e-11e8-9db7-cca9f979aa6e.png)
Yes, you can use a intervalometer to take many photos, but then you have to _manually_ stitch them together in your video editing software. If you've ever done this _manually_ you know how tedious it is.

Sony _used_ to have the Time-lapse functionality in their "PlayMemories Camera App" for **£7.99**:
![image](https://user-images.githubusercontent.com/194400/49102635-3fc68080-f271-11e8-90dd-5de30ab4bcf2.png)
Sony could _easily_ have included this functionality in their Camera!! 😕 

If you don't _want_ to be _able_ to do a Hyperlapse, then the Sony is "fine" ...
[![image](https://user-images.githubusercontent.com/194400/49102036-9fbc2780-f26f-11e8-9ced-7be3703f18c2.png)](https://youtu.be/DcylVx2ex78)
https://youtu.be/DcylVx2ex78 _seriously_ watch it! (_decide for yourself if you "**need**" **hyperlapse**_). 

https://fstoppers.com/originals/eight-things-stopping-sony-a7-iii-being-perfect-camera-278341
![image](https://user-images.githubusercontent.com/194400/49102748-8fa54780-f271-11e8-9db4-7a1d49b3fd45.png)

**Comment by nelsonic** [comment]
Jared Polin makes it clear in this comparison that ***Dual Pixel VIDEO Autofocus*** is _better_ on the Canon:
[![image](https://user-images.githubusercontent.com/194400/49105197-e57cee00-f277-11e8-8267-6904cc28ddb9.png)](https://youtu.be/c8gRKB3WMdg?t=442)
https://youtu.be/c8gRKB3WMdg?t=442

**Comment by nelsonic** [comment]
This is probably the most _balanced_ video on Why Sony for _Professional_ photography/video:
[![image](https://user-images.githubusercontent.com/194400/49112490-d7849880-f28a-11e8-856d-3b1c6a8b1c46.png)](https://youtu.be/wI656MIUCsg)
https://youtu.be/wI656MIUCsg

Sean Tucker makes a _compelling_ case for the Sony A7 III for _his_ use-case(s). 
I feel that he is _ignoring_ the Video Autofocus and Fold-out screen because _he_ doesn't _need_ them.

To be clear, I have already _ordered_ a DSLR Video Monitor #51 which I will be able to use with the **7D**.
So the lack of an articulated screen could be _partially_ ignored for "at home" use. 
But if I was going on Holiday with the camera and wanted to capture self video,
I would _probably_ not be taking a _separate_ screen just to be able to frame a self shot.
Given that I'm not _planning_ on going on Holiday any time soon, and I will have a tripod or gimbal #50 
in Braga, I feel that the ***Autofocus*** is the last remaining feature to be considered.

**Comment by nelsonic** [comment]
Sony 24mm f1.4 GM vs Sigma 24mm f1.4 ART: Comparison & Review
[![image](https://user-images.githubusercontent.com/194400/64472550-056f0580-d158-11e9-943e-2ddeccf71477.png)](https://youtu.be/1U-hsH-lKHM)
https://youtu.be/1U-hsH-lKHM

This is a good comparison. 
(_I'm still thinking of getting the Sony GM Lens ... I might need to sell a kidney or lung for it..._)
