### ISSUE TITLE
Which Computer for Video Editing?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/video#55]
Editing video requires a decent machine, I find that even editing 1080p on my _current_ mac requires rendering time and exporting videos takes _hours_. I feel that a high-spec machine is worthwhile investment to save _time_ and reduce frustration.

My _first_ instinct is to buy a **2018 Mac Mini** because it's compact and RAM-upgradeable.
+ 3.2GHz 6‑core 8th‑generation Intel Core i7 (Turbo Boost up to 4.6GHz)
+ 8GB 2666MHz DDR4
+ Intel UHD Graphics 630
+ 512GB SSD storage (_non upgradeable but PCI-E so v. Fast!_)
+ Gigabit Ethernet (_this is probably "enough" considering our network cabling is 1GB Cat 6E_)

https://www.apple.com/shop/buy-mac/mac-mini/3.0ghz-6-core-processor-with-turbo-boost-up-to-4.1ghz-256gb#
![image](https://user-images.githubusercontent.com/194400/49373650-ba225500-f6f6-11e8-919c-6af465d8e911.png)

https://www.apple.com/uk/shop/buy-mac/mac-mini/3.0ghz-6-core-processor-with-turbo-boost-up-to-4.1ghz-256gb **£1,429** which is ***$1,817.25** USD 😕 
![image](https://user-images.githubusercontent.com/194400/49373692-da521400-f6f6-11e8-826f-0b688ad9e370.png)

While it is certainly _possible_ to upgrade the RAM, it's also _expensive_ given that it only has two slots:
![image](https://user-images.githubusercontent.com/194400/49375565-93ffb380-f6fc-11e8-82ad-1230681dd12c.png)
see: https://appleinsider.com/articles/18/11/08/how-to-upgrade-the-ram-on-the-new-2018-mac-mini

My biggest gripe with the Mac Mini _besides_ the _price_ is the integrated graphics chip:
https://www.notebookcheck.net/Intel-UHD-Graphics-630-GPU-Benchmarks-and-Specs.257928.0.html
Which for Davinci Resolve is a non-starter (_Resolve uses the GPU for rendering_).

[![image](https://user-images.githubusercontent.com/194400/49374291-cdcebb00-f6f8-11e8-80f1-9fd6abf12cc6.png)](https://youtu.be/qzSYLdVjFqA)
https://youtu.be/qzSYLdVjFqA

The GPU _shares_ system memory (RAM), so if you are running a demanding app like Reason, Logic, FCP or Resolve and have a few videos in your timeline, RAM will rapidly be exhausted!

By contrast buying an _older_ Mac "Pro" might be a _better_ option for video editing: 
https://www.ebay.co.uk/itm/Mac-Pro-5-1-2012-3-46GHz-12-Core-128GB-RAM-GTX-980-250GB-SSD-USB3/162931000593
![image](https://user-images.githubusercontent.com/194400/49374537-898fea80-f6f9-11e8-9cae-f07c4276d39a.png)
It comes with **128GB RAM** and a GTX 980 **4GB** Graphics Card!
![image](https://user-images.githubusercontent.com/194400/49375328-e42a4600-f6fb-11e8-8106-d76bed7ed676.png)

a _Third_ option is to build a "Hackintosh" https://github.com/nelsonic/nelsonic.github.io/issues/510
But given that Davinci Resolve can run on Linux ... (_a Mac may no longer be necessary!!_)
[![image](https://user-images.githubusercontent.com/194400/49374751-366a6780-f6fa-11e8-82c5-49cb39fd2828.png)](https://youtu.be/CuEPD0i9gmk)
https://youtu.be/CuEPD0i9gmk

http://www.logicalincrements.com/articles/videoediting
![image](https://user-images.githubusercontent.com/194400/49374819-6ca7e700-f6fa-11e8-823d-42d8d23d9632.png)

> If you plan to edit with Resolve, you absolutely need a powerful graphics card, as that software is powered primarily by GPU instead of CPU.
![image](https://user-images.githubusercontent.com/194400/49374966-d58f5f00-f6fa-11e8-83d6-b63d0ed01818.png)

[![image](https://user-images.githubusercontent.com/194400/49377033-f5298600-f700-11e8-9916-c96777a3b58e.png)](https://youtu.be/7-s04b5zel8)
https://youtu.be/7-s04b5zel8

# _Next Action_

+ [ ] Determine how much Linux PC we can build for €1000 and €2000
+ [ ] Calculate the ***Power Consumption*** of the PSU for the custom-build. 
e.g if it's 1kW it costs €0.16/hour to run i.e. €2/day 
  it might be worth it to buy the Mac Mini which only consumes 85W ... 🤔 

Preferably:
+ [ ] Nice-ish but budget-friendly case with expansion options. (_ideally lockable_)
+ [ ] AMD Ryzen processor
+ [ ] Good Graphics Card
+ [ ] 64GB or even 128GB RAM
+ [ ] SSD (_I've already ordered a good one on "Brack Friday"..._) 
+ [ ] Use whatever keyboard and mouse combo we have "lying around" until we feel the need to upgrade.

+ [ ] Which **Linux OS** is best for simplicity and workflow UI?

**Comment by nelsonic** [comment]
@edwardcodes once you have learned a bit of Davinci Resolve #53 
and felt the "bottleneck" of having an "older" (_slower_) PC for video editing,
please consider dedicating a few hours to researching custom-building PCs from components
so that we have 4K capable video editing stations. 
(_**note**: we aren't going to switch to 4K because it's a **waste** of disk space! 
but there will be certain situations where we will want to have 4K for videos I'm planning,
and having powerful video editing computer(s) is a good idea to not waste time waiting for renders_)

Come back to this in the "break" between Christmas and New year. 😉

**Comment by nelsonic** [comment]
I _briefly_ considered a 2017 iMac:
+ 4.2GHz i7 (Quad Core)
+ 64GB RAM
+ 2TB Fusion Drive
+ Radeon 580 **8GB**
https://www.ebay.co.uk/itm/iMac-27-2017-4-2GHz-i7-64GB-RAM-2TB-Fusion-Drive-Radeon-580-8GB/152787136172
![image](https://user-images.githubusercontent.com/194400/49689966-26e78600-fb21-11e8-89b3-daf3f51d07a7.png)

But after watching this comparison I feel that the Mac Pro is better value for money and _faster_ ...
[![image](https://user-images.githubusercontent.com/194400/49689488-da4c7c80-fb19-11e8-9187-c42eb4f229c6.png)](https://youtu.be/LmOVfR_0OcY)
https://youtu.be/LmOVfR_0OcY

This one has an _insanely_ powerful graphics card:
https://www.ebay.co.uk/itm/Apple-Mac-Pro-5-1-2012-3-46GHz-12-Core-128GB-RAM-Titan-Xp-12GB-1TB-SSD/152713349912
![image](https://user-images.githubusercontent.com/194400/49689961-10412f00-fb21-11e8-8677-8ce692a5b216.png)

This GPU is _probably_ massively overkill ... but this is how much it costs alone:
https://www.amazon.com/NVIDIA-TITAN-Graphics-Card-900-1G611-2530-000/dp/B0757DSD6D
![image](https://user-images.githubusercontent.com/194400/49691102-2a840880-fb33-11e8-9d02-89e13916cd26.png)

For comparison, a PC with a _similar_ amount of RAM, CPU and GPU costs almost $5.5k:
https://silentpc.com/elite-pcs/photo-video-editing-pc
![image](https://user-images.githubusercontent.com/194400/49691105-366fca80-fb33-11e8-87f0-f1b1fc7c79c9.png)
![image](https://user-images.githubusercontent.com/194400/49691112-5e5f2e00-fb33-11e8-963c-ad7d0fa45c7b.png)

I've watched a few videos on Video Editing on Linux and the codec/transcoding/drivers issues
seem to be more hassle than it's worth to use an Open Source OS ...
[![image](https://user-images.githubusercontent.com/194400/49691124-99f9f800-fb33-11e8-9fe8-70d05248c565.png)](https://youtu.be/hksW66jw1jA)
https://youtu.be/hksW66jw1jA

So I'm increasingly thinking that a Mac Pro is the way to go ... 🤔

**Comment by ghost** [comment]
@nelsonic agreed 👍

**Comment by nelsonic** [comment]
_Predictably_, I've done a _ton_ more research into this ... 
a more affordable way of having the _best_ graphics card on _any_ (_recent_) Mac: **_External_ GPU**!

This is a good article on the "_usefulness_" of eGPUs with Mac OS:
https://hackernoon.com/egpu-with-macos-how-useful-is-one-really-68f7651cba24
The eGPU described by Alex Wulff's article is the GIGABYTE **Gaming Box** Radeon RX 580 **8GB**

https://www.amazon.com/GIGABYTE-Gaming-Graphic-Card-GV-RX580IXEB-8GD/dp/B07CCK527Y/
![image](https://user-images.githubusercontent.com/194400/49724723-e04d7500-fc61-11e8-94a1-64fa47dfebae.png)

> **Note** I also read: https://www.gamingscan.com/best-external-graphics-card
> But most external graphics cards use _insane_ amounts of Power! 450W! i.e. 8c/hour. €1/day

This Mac Support article: https://support.apple.com/en-us/HT208897 has a **good _summary_**:
![image](https://user-images.githubusercontent.com/194400/49720964-07ec0f80-fc59-11e8-8c88-fb1ee7bb2342.png)

Thunderbolt 3 is a _version_ of USB-C https://support.apple.com/en-gb/HT208368
![image](https://user-images.githubusercontent.com/194400/49723399-97e08800-fc5e-11e8-9784-02302280dac0.png)
Only available on MacBook Pro 2016< and iMac 2017< 

_Way_ more detail on **Thunderbolt 3**: https://thunderbolttechnology.net/blog/thunderbolt-3-usb-c-does-it-all
![image](https://user-images.githubusercontent.com/194400/49721055-48e42400-fc59-11e8-9733-7a9699f64419.png)

Annoyingly "Not all USB-C ports are the same" ... 🙄 
[![image](https://user-images.githubusercontent.com/194400/49728432-a2088380-fc6a-11e8-83a3-418edacbcc41.png)](https://youtu.be/xLs_0wHcv4A)
https://youtu.be/xLs_0wHcv4A

Blackmagic eGPU 3 month Review - Video Editors BEWARE!
[![image](https://user-images.githubusercontent.com/194400/49728747-7df97200-fc6b-11e8-844e-6f2919f6bd69.png)](https://youtu.be/pDKUn05ZAnI)
https://youtu.be/pDKUn05ZAnI
Max tested the eGPU with 3 different MacBook Pro Configurations:
![image](https://user-images.githubusercontent.com/194400/49728973-0ed04d80-fc6c-11e8-809f-37f52520fea8.png)
And with 3 different video editing programs: Premier Pro, Final Cut and Resolve.
![image](https://user-images.githubusercontent.com/194400/49729435-615e3980-fc6d-11e8-8d94-8756a6bd37e2.png)
"_The fastest laptop actually got **slower** with the eGPU_" ... baring in mind that was the **$3,500** i9 beast!!

**Pros**:
+ Very quiet in operation (_well designed cooling vents and silent fans_)
+ Designed _specifically_ by Blackmagic Design for use with Resolve.

**Cons**:
+ Cannot upgrade the graphics card in the unit.
+ More expensive than buying a housing unit and separate (_upgradeable_) GPU.

Search eBay for "blackmagic egpu" https://www.ebay.com/sch/i.html?_nkw=blackmagic+egpu _example_:
![image](https://user-images.githubusercontent.com/194400/49721766-f1df4e80-fc5a-11e8-96d8-b4c62bc81ed0.png)

Alternative proposed by Max:
https://www.bhphotovideo.com/c/product/1338299-REG/sonnet_gpu_350w_tb3z_egfx_breakaway_box_350.html
![image](https://user-images.githubusercontent.com/194400/49730367-0ed24c80-fc70-11e8-819f-59d039ebbf5f.png)



This "research" is taking up _way_ too much of my mind-time ... ⏳ 🙄 (`#OneTrackMind` ...)

# Decision

So I've made the call and ordered the _best_ (_value for money_) **MacBook Pro** for video editing.
I ordered a 2017 MacBook Pro 15" with Touch Bar and 16GB RAM:
![image](https://user-images.githubusercontent.com/194400/49732749-8061c900-fc77-11e8-8588-e89c3a7f7104.png)

![image](https://user-images.githubusercontent.com/194400/49731980-f4e73880-fc74-11e8-98a6-ca90adf9794e.png)
This is the best value-for-money ***portable*** video editing machine. 
It is _far_ more portable than a comparable Mac Pro and since the CPU architecture is _far_ more recent the main "_bottleneck_" is avoided. 

This Laptop will be _loaned_ to whoever is doing the video editing for @dwyl videos
For the foreseeable future that person will be @edwardcodes 
(_who already has a MacBook Pro but has seen "frame dropping" while editing in Resolve 15 ..._)
Edu will track his experience while rendering and exporting 1080p video.
If the editing experience is "sluggish" we can _consider_ an external GPU (_see above_).

Also, given that this laptop still costs **£1,869** direct from Apple:
https://www.apple.com/uk/shop/product/FPTR2B/A/Refurbished-154-inch-MacBook-Pro-28GHz-Quad-core-Intel-Core-i7-with-Retina-display-Space-Gray
![image](https://user-images.githubusercontent.com/194400/49732448-acc91580-fc76-11e8-826e-f09895e6a28d.png)
![image](https://user-images.githubusercontent.com/194400/49732529-e8fc7600-fc76-11e8-8cb8-074441b2f21a.png)

I feel that there is **_zero_ risk** in this purchase.
If Edu (_or whoever is doing our full-time video editing_) "out-grows" this machine,
we can _easily_ sell it on without losing much money.
The fact is that this machine will be _many_ times better than Edu's MBP 13" 2012 for video.
His machine is "fine" for writing code, but it "chokes" _badly_ on rendering in Resolve.
I'm _confident_ that he will have a _superior_ experience with the MBP 15" 2017.

Done. 

> NOTE: @edwardcodes I'm still _tempted_ by a Mac Pro (_desktop_) for myself.
But I'm going to _resist_ the temptation to spend more money until the MacBook Pro 15 arrives 
and we test it _together_. If the rendering time is "OK" and you're happy to do _most_ of the editing for the dwyl/braga videos, then we can "get by" with only the Laptop. 👍

**Comment by nelsonic** [comment]
Original Listing: https://www.ebay.co.uk/itm/113429285070
![image](https://user-images.githubusercontent.com/194400/49732976-30373680-fc78-11e8-89ad-e43b6222a5ba.png)

Not too much description:
> Pristine condition
> Comes with charger and non Apple postage box

But that's all I really need to know.

**Comment by nelsonic** [comment]
Recommend watching this:
[![image](https://user-images.githubusercontent.com/194400/49733867-93c26380-fc7a-11e8-9589-2d034f0c27cc.png)](https://youtu.be/6ix2Xg2I0Jo)
https://youtu.be/6ix2Xg2I0Jo

Conclusion: _yes_ you can spend less cash on building your own PC,
but the "full package" of a Mac has a "synergy". 

When we "_outgrow_" the MacBook Pro 15, we will re-visit this issue. 
I think we're going to be "OK" for 1080p video editing for the next few months. 👍

**Comment by nelsonic** [comment]
Next: #86 💭
