### ISSUE TITLE
Can we update a video that has already been published on YouTube?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/video#9]
Looks like it's possible:
http://www.reelseo.com/edit-videos-with-youtube/

**Comment by ghost** [comment]
@nelsonic those are mostly only aesthetic changes - footage stabilisation etc. If you need to change the actual content then it needs to be taken down and reuploaded again (highly annoying and very different to the iterative way a developer works).

**Comment by nelsonic** [comment]
Makes sense that they wouldn't allow people to update videos. 
thanks for confirming. 
closing. 👍
